// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // La configuration de Prisma est maintenant alignée pour utiliser systématiquement
    // la base de données distante PostgreSQL, comme défini par DATABASE_URL_REMOTE.
    // La base de données locale SQLite (DATABASE_URL_LOCAL) est gérée par le code Tauri.
    url: process.env.DATABASE_URL_REMOTE ?? '',
  },
});
